# Generated by Django 4.0.4 on 2022-05-25 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=13)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('rut', models.IntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='usuarios/perfil')),
                ('celular', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=8)),
                ('estado', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='eas_coelemu_app.rol')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
