# Generated by Django 4.0.4 on 2022-06-15 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eas_coelemu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preciogas',
            options={'ordering': ['created_at']},
        ),
    ]
