# Generated by Django 4.0.4 on 2022-06-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eas_coelemu_app', '0003_alter_preciogas_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descuentoaplicable',
            old_name='calificacion',
            new_name='calificacion_base',
        ),
        migrations.AddField(
            model_name='descuentoaplicable',
            name='calificacion_tope',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
