# Generated by Django 4.0.4 on 2022-06-19 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eas_coelemu_app', '0004_rename_calificacion_descuentoaplicable_calificacion_base_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descuentoaplicable',
            old_name='decuento',
            new_name='descuento',
        ),
    ]
