# Generated by Django 4.0.4 on 2022-06-19 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eas_coelemu_app', '0005_rename_decuento_descuentoaplicable_descuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CantidadConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_canvenios', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cantidadconvenio', to='eas_coelemu_app.usuario')),
            ],
        ),
    ]
