# Generated by Django 4.0.4 on 2022-06-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eas_coelemu_app', '0006_cantidadconvenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantidadconvenio',
            name='estado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
