# Generated by Django 4.0.4 on 2022-06-28 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eas_coelemu_app', '0009_grupofamiliar_integrantegrupofamiliar_beneficiario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupofamiliar',
            old_name='rhs_archivo',
            new_name='rsh_archivo',
        ),
    ]
